### PR TITLE
Updated-hardware-connector-for-sensors

### PR DESCRIPTION
**Pull request by nate1911**
#20

### CODE REVIEW

**Review by BlieNuckel — CHANGES_REQUESTED** [review]
The hardware serial outputs "pin,value" as soon as a state updates. The function "get_sensor_data" seems to be expecting a command to trigger the sensor data being fetched.

The code must be changed to always listen for updates in a listener and then call on "self.on_send" when a new piece of data is received. Similarly it must pause the listening for sensor updates when an action is being sent

**Comment by nate1911** [comment]
Noted

**Review by BlieNuckel — CHANGES_REQUESTED** [review]
I think we might need to implement some threading of some kind, as the current while loop will just block the entire backend.

Also on_send must be a Callable[[int, int], None] to function with the existing code. If you want to keep it as Callable[[str, float], None] you'll need to also edit the existing code in main.py and add it with your commit.

It's really hard to catch some of these things while not really being able to test it, so if you feel like you need it you could create another serial connector python script (that you can just run manually) and maybe send data to act as the hardware or something.

You can use the main backend branch to be able to run the server in the first place, as it needs to be able to connect to some sort of sockets.

**Review by BlieNuckel — APPROVED** [review]
The changes look good and should support integration with the main flow.

Currently not integrated fully, I will personally handle this when the hardware is present for testing purposes.

There may arise some issues between threading and the tornado.IOLoop currently used for our serial connections, but this will be handled during integration.

Good job!

**Pull request merged**
